# does not crash cuz no import wtf

class ContentShaper(Protocol):
    def normalize_file_spec(self, item: str | dict) -> tuple[str, int | None]: ...
    def apply_truncation(self, content: str, spec: TruncationSpec | None) -> str: ...
    def hydrate(
        self, delim: str, template: str, replacements: dict[str, str]
    ) -> str: ...