filesets:
  core: {includes: [clanker.py, models.py], excludes: []}
  ad-hoc: {includes: [utilities.py, adapters.py], excludes: []}

domains:
- name: script-dev
  resolvers:
    - { id: repo_content, type: repo_content, fileset: core }
    - { id: domain_fragments, type: multi-document-retrieval, files: [backlog.cdoc], }
    
  prompts:
    - name: plan
      render:
        resolvers:
          - { id: prompt_fragments, type: multi-document-retrieval, files: [plan-mode.md, backlog-output-instructions.md] }

    - name: bl-impl
      render:
        resolvers:
          - {id: prompt_fragments, type: multi-document-retrieval, files: [do-mode.md, code-output-instruction.md]}

    - name: bl-drain
      render:
        resolvers:
          - {id: prompt_fragments, type: multi-document-retrieval, files: [doc-management-mode.md, {file: project-history.cdoc, tail_lines: 8}, history-output-instructions.md]}
        
    - name: ad-hoc
      render:
        resolvers:
          - { id: base_fragments, type: multi-document-retrieval, files: [] }
          - { id: domain_fragments, type: multi-document-retrieval, files: [] }
          - { id: prompt_fragments, type: multi-document-retrieval, files: [] }
          - { id: repo_content, type: repo_content, fileset: ad-hoc }

- name: north-star
  resolvers:
    - { id: domain_fragments, type: multi-document-retrieval, files: [north-star.md] }
  prompts:
    - name: ns-plan
      render:
        resolvers:
          - { id: prompt_fragments, type: multi-document-retrieval, files: [] }
          - { id: repo_content, type: repo_content, fileset: core }

- name: config-dev
  resolvers:
    - { id: domain_fragments, type: multi-document-retrieval, files: [config.yaml, system_cfg.yaml, shared_cfg.yaml] }
  prompts:
    - name: config-dev
      render:
        resolvers:
          - { id: prompt_fragments, type: multi-document-retrieval, files: [config-development-instructions.md] }
          - { id: repo_content, type: repo_content, fileset: core }

- name: debloat
  resolvers:
    - { id: domain_fragments, type: multi-document-retrieval, files: [domain-debloat.md] }
  prompts:
    - name: debloat
      render:
        resolvers:
          - { id: prompt_fragments, type: multi-document-retrieval, files: [debloat-instructions.md] }
          - { id: repo_content, type: repo_content, fileset: core }